version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules  # evita sobrescrever node_modules com a pasta vazia local
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
