version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
      - ./frontend/.env:/app/.env 
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
