version: "3.8"

services:
  original-frontend:
    build:
      context: ./original-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./original-frontend:/app
      - /app/node_modules 
      - ./original-frontend/.env:/app/.env 
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./original-frontend
          target: /app

  version-1:
    build:
      context: ./version-1
    ports:
      - "5174:5173"
    volumes:
      - ./version-1:/app
      - /app/node_modules
      - ./version-1/.env:/app/.env
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./version-1
          target: /app
