sonar.projectKey=tcc-frontend-version-2
sonar.projectName=TCC Frontend - Version 2
sonar.projectVersion=2
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist-ssr/**,**/coverage/**,**/.scannerwork/**
